spring:
  application:
    name: book
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
  client:
    serviceUrl:
      defaultZone: http://192.168.3.201:1001/eureka/,http://192.168.3.202:1001/eureka/,http://192.168.3.203:1001/eureka/
server:
  port: 8001
management:
  endpoint:
    health:
      show-details: always