server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
      - id: limit_route
        uri: http://127.0.0.1:8001
        predicates:
          - Path=/store/**
        filters:
          - RewritePath=/store/(?<segment>.*), /$\{segment}
          - AddRequestHeader=Hello, World
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@urlKeyResolver}'
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 10
  redis:
    host: 192.168.3.111
    port: 6379
    database: 0