server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://118.25.195.209:3306/cloud_common?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yxx@144830
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  thymeleaf:
    cache: false
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: limit_route
#        uri: http://127.0.0.1:9000
        uri: lb://book
        predicates:
        - Path=/book/**
        filters:
        # 转发请求时去掉1级前缀
        - StripPrefix=1
        # 重写
        #        - RewritePath=/store/(?<segment>.*), /$\{segment}
        - AddRequestHeader=test, hello

#        - name: RequestRateLimiter
#          args:
#            key-resolver: '#{@urlKeyResolver}'
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 10
  redis:
    host: 192.168.3.188
    port: 6379
    password:
    database: 0
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.3.201:1001/eureka/,http://192.168.3.202:1001/eureka/,http://192.168.3.203:1001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
auth:
  redisHost: 192.168.3.188
  redisPassword:
  redisDb: 3