spring:
  application:
    name: eureka-server
server:
  port: 1001
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0