spring:
  rabbitmq:
    username: u
    password: 123456
    virtual-host: /
    addresses: jd.dlj1.cn:5672
  cloud:
    stream:
      bindings:
        input:
          destination: test
          group: queue
          binder: rabbit
          consumer:
            concurrency: 2
        output:
          destination: test
          binder: rabbit